version: "3.8"
services:
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      DATABASE_HOST: 192.168.1.200
      POSTGRES_DB: global
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5432:5432"
networks:
  my-network:
    ipam:
      config:
        - subnet: 172.24.0.0/16


    